create table foods (price integer, id bigint generated by default as identity, image varchar(255), title varchar(255), primary key (id));
create table foods (price integer, id bigint generated by default as identity, image varchar(255), title varchar(255), primary key (id));
create table foods (price integer, id bigint generated by default as identity, image varchar(255), title varchar(255), primary key (id));
create table foods (price integer, id bigint generated by default as identity, image varchar(255), title varchar(255), primary key (id));
